"""Episode environments over the functional core: tasks, sensors, episode functions, baseline
policies, families of airframes, and weather. See ``docs/environments.md``."""

from cascade.env.baselines import cascade_policy, transition_policy
from cascade.env.episode import (
    EnvState,
    EpisodeConfig,
    action_size,
    action_to_control,
    control_to_action,
    current_environment,
    observation,
    reset,
    rollout_actions,
    rollout_policy,
    step,
)
from cascade.env.family import Family, family_member, sample_family, stack_pytrees
from cascade.env.sensors import SensorNoise, sensor_noise
from cascade.env.tasks import (
    HoverTask,
    Reference,
    ReferenceFlight,
    Task,
    TrackingTask,
    TransitionTask,
    hover_reference,
    hover_task,
    reference_speed,
    tracking_task,
    transition_task,
    trimmed_reference,
)
from cascade.env.weather import (
    WeatherCondition,
    WeatherRecords,
    mean_wind_ned,
    sample_weather,
    sample_weather_uniform,
    weather_classes,
    weather_condition,
)

__all__ = [
    "EnvState",
    "EpisodeConfig",
    "Family",
    "HoverTask",
    "Reference",
    "ReferenceFlight",
    "SensorNoise",
    "Task",
    "TrackingTask",
    "TransitionTask",
    "WeatherCondition",
    "WeatherRecords",
    "action_size",
    "action_to_control",
    "cascade_policy",
    "control_to_action",
    "current_environment",
    "family_member",
    "hover_reference",
    "hover_task",
    "mean_wind_ned",
    "observation",
    "reference_speed",
    "reset",
    "rollout_actions",
    "rollout_policy",
    "sample_family",
    "sample_weather",
    "sample_weather_uniform",
    "sensor_noise",
    "stack_pytrees",
    "step",
    "tracking_task",
    "transition_policy",
    "transition_task",
    "trimmed_reference",
    "weather_classes",
    "weather_condition",
]
